server:
  port: 8080
spring:
  thymeleaf:
    cache : false
    mode: HTML5
  neo4j:
    url: bolt://127.0.0.1:7687
    username: neo4j
    password: logic
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/know?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    type: com.zaxxer.hikari.HikariDataSource
mybatis:
  typeAliasesPackage: com.warmer.kgmaker.entity
  mapperLocations: classpath*:/mapping/*.xml
#配置分页插件pagehelper
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
