server:
  port: 8080
spring:
  thymeleaf:
    cache : false
    mode: HTML5
  neo4j:
    url: bolt://127.0.0.1:7687
    username: neo4j
    password: logic
  datasource:
    url: jdbc:mysql://localhost:3306/hanweb?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false
    username: root
    password: 123456
  jpa:
      database: MySQL
      database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
      show-sql: true
      hibernate:
        ddl-auto: update
  data:
    neo4j:
      uri: bolt://127.0.0.1:7687
      username: neo4j
      password: logic
      open-in-view: false
mybatis:
  typeAliasesPackage: com.warmer.kgmaker.entity
  mapperLocations: classpath*:/mapping/*.xml
#配置分页插件pagehelper
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
